name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

  http: ^1.4.0
  go_router: ^16.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  get_storage: ^2.1.1
  connectivity_widget: ^3.0.0
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  hive_ce_generator: ^1.9.2
  riverpod_generator: ^2.6.3
  faker: ^2.2.0
  golden_toolkit: ^0.15.0
  mockito: ^5.4.6
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/pokemon_type_logos/big_white/
    - assets/images/pokemon_type_logos/small_coloured/